### ISSUE TITLE
Add functionality to track log file position

### ISSUE THREAD

**Issue by danlsgiga** [Graylog2/collector#82] opened 2016-03-01 20:26 UTC
Would be awesome to have the collector to track the log file position to be able to recover any entries logged while the daemon was down. This way we won't lose any messages.
I know that Logstash has it using the sincedb functionality.

Ref: https://www.elastic.co/guide/en/logstash/current/plugins-inputs-file.html

**Comment by joschi** [comment] 2016-03-01 20:34
Duplicate of #26.

**Closed by joschi** 2016-03-01 20:34 UTC
