### ISSUE TITLE
FILTER / GROK support on client side

### ISSUE THREAD

**Issue by tomlux** [Graylog2/collector#83] opened 2016-03-10 08:02 UTC
Hy,
I would appreciate if we could so similar filtering and implement Grok patterns on client side as it's possible in the logstash:
 https://www.elastic.co/guide/en/logstash/current/filter-plugins.html

Thanks,
 Tom

**Comment by joschi** [comment] 2016-03-10 09:35
Duplicate of #27.

**Closed by joschi** 2016-03-10 09:35 UTC
